# Generated by Django 4.2.8 on 2024-01-07 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='sulg',
            new_name='slug',
        ),
    ]
