# Generated by Django 4.2.8 on 2024-01-16 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_brand_slug_alter_colour_slug_alter_item_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='slug',
            new_name='itm_slug',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='slug',
            new_name='prod_slug',
        ),
    ]
