# Generated by Django 4.2.8 on 2024-01-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_slug_item_itm_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
