# Generated by Django 4.2.8 on 2024-01-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='files',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='static/products/', verbose_name='Images'),
        ),
    ]
